/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIBarButtonItem.h>

@class NSDate, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface NotesRefreshController : UIBarButtonItem {
	NSMutableDictionary* _lastNotesRefreshDates;
	NSDate* _lastStoresListRefreshDate;
}
+(id)sharedInstance;
-(void).cxx_destruct;
-(void)refreshNotesForCollectionWithId:(id)anId;
-(void)refreshAllNotesIfNeeded;
-(BOOL)notesNeedRefreshForCollectionWithId:(id)anId;
-(BOOL)notesNeedRefresh;
-(void)refreshStoresList;
-(void)refreshOrphanedAccounts;
-(BOOL)storesListNeedsRefresh;
-(id)_accountsManager;
@end

