/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileNotes-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface NotesUITableViewCell : XXUnknownSuperclass {
	float _topMargin;
}
@property(assign, nonatomic) float topMargin;
+(CGSize)defaultAccessoryViewSize;
+(CGPoint)accessoryViewImageOffset;
+(BOOL)hasCustomAccessoryView;
-(void)layoutSubviews;
-(CGRect)boundsForContent;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

