/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIViewController;
@protocol UISearchDisplayDelegate;

__attribute__((visibility("hidden")))
@interface NotesSearchTableViewController : XXUnknownSuperclass {
	UIViewController<UISearchDisplayDelegate>* _searchContentsController;
}
@property(assign) UIViewController<UISearchDisplayDelegate>* searchContentsController;
-(void)searchDisplayController:(id)controller willHideSearchResultsTableView:(id)view;
-(void)searchDisplayController:(id)controller willShowSearchResultsTableView:(id)view;
-(void)searchDisplayControllerDidEndSearch:(id)searchDisplayController;
-(BOOL)searchDisplayController:(id)controller shouldReloadTableForSearchString:(id)searchString;
-(void)searchDisplayControllerWillEndSearch:(id)searchDisplayController;
-(void)searchDisplayControllerWillBeginSearch:(id)searchDisplayController;
-(Class)_resultsTableViewClass;
@end

