/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol NoteContentLayerDelegate <NSObject>
-(void)noteContentLayer:(id)layer containsCJK:(BOOL)cjk;
-(void)noteContentLayer:(id)layer setEditing:(BOOL)editing animated:(BOOL)animated;
-(void)noteContentLayerContentDidChange:(id)noteContentLayerContent;
@end

