/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileNotes-Structs.h"
#import "NotesUITableViewCell.h"

@class UILabel, NSString;

__attribute__((visibility("hidden")))
@interface NoteCell : NotesUITableViewCell {
	UILabel* _titleLabel;
	UILabel* _dateLabel;
	CGRect _lastFrame;
	NSString* _summary;
	BOOL _containsCJK;
	BOOL _useAlternateTextColor;
}
@property(assign) BOOL useAlternateTextColor;
+(CGSize)defaultAccessoryViewSize;
+(CGPoint)accessoryViewImageOffset;
+(BOOL)hasCustomAccessoryView;
-(void).cxx_destruct;
-(id)_automationValue;
-(id)_automationID;
-(void)layoutSubviews;
-(void)hideDate:(BOOL)date;
-(void)setContainsCJK:(BOOL)cjk;
-(void)setSummary:(id)summary;
-(void)setDate:(id)date;
-(void)setTitle:(id)title;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
-(id)_dateTextColor:(BOOL)color;
-(id)_titleTextColor:(BOOL)color;
-(void)updateTitleFont;
@end

