/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileNotes-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, UIImageView;
@protocol NotesBackgroundViewDelegate;

__attribute__((visibility("hidden")))
@interface NotesBackgroundView : XXUnknownSuperclass {
	id<NotesBackgroundViewDelegate> _delegate;
	UIImageView* _topEdge;
	UIImageView* _bottomEdge;
	UIImageView* _gradientBottom;
	UIView* _navView;
	int _style;
	unsigned _inLandscape : 1;
}
@property(assign, nonatomic) id<NotesBackgroundViewDelegate> delegate;
+(float)defaultBottomMargin;
-(void).cxx_destruct;
-(id)bottomView;
-(float)bottomMargin;
-(void)setNavigationView:(id)view;
-(void)addContentView:(id)view;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame style:(int)style fadeBottom:(BOOL)bottom delegate:(id)delegate;
-(id)copyGradientBottomWithImage:(id)image forBounds:(CGRect)bounds;
-(void)setImage:(id)image;
@end

