/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIActivityViewController.h>

@class NotesDisplayController;

__attribute__((visibility("hidden")))
@interface NotesActivityViewController : UIActivityViewController {
	NotesDisplayController* _displayController;
}
@property(retain, nonatomic) NotesDisplayController* displayController;
-(void).cxx_destruct;
-(void)_prepareActivity:(id)activity;
-(BOOL)_shouldShowSystemActivity:(id)activity;
@end

