/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileNotes-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView;

__attribute__((visibility("hidden")))
@interface NotesTableView : XXUnknownSuperclass {
	UIImageView* _background;
	UIImageView* _topEdge;
	UIImageView* _bottomEdge;
	BOOL _isLandscape;
}
-(void).cxx_destruct;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame style:(int)style;
@end

