/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileNotes-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UILabel, NSDate;

__attribute__((visibility("hidden")))
@interface NoteDateView : XXUnknownSuperclass {
	NSDate* _date;
	UILabel* _userFriendlyLabel;
	UILabel* _dateLabel;
	float _marginLeft;
	unsigned _setToNil : 1;
}
-(void).cxx_destruct;
-(void)fadeOutFinished;
-(void)setMarginLeft:(float)left;
-(void)setDate:(id)date;
-(void)updateLabels;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

