/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileNotes-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIBezierPath;

__attribute__((visibility("hidden")))
@interface NotesAccountsSelectedBackgroundView : XXUnknownSuperclass {
	unsigned _rectCorners;
	UIBezierPath* _cachedPath;
	CGRect _cachedRect;
}
-(void).cxx_destruct;
-(void)drawRect:(CGRect)rect;
-(id)initWithRoundedTopCorners:(BOOL)roundedTopCorners bottomCorners:(BOOL)corners;
@end

