/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol NotesListAuthority
-(id)currentList;
-(void)directionButtonClicked:(int)clicked forNote:(id)note;
-(void)shouldEnableLeftButton:(BOOL*)button rightButton:(BOOL*)button2 forNote:(id)note;
-(void)queryForNewItem;
@end

