/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MobileNotes-Structs.h"
#import "UITextViewDelegate.h"

@class UIView, UITextView, NSString;
@protocol NoteContentLayerDelegate;

__attribute__((visibility("hidden")))
@interface NoteContentLayer : XXUnknownSuperclass <UITextViewDelegate> {
	UITextView* _textView;
	UIView* _ruleView;
	id _delegate;
	BOOL _containsCJK;
	unsigned _handlingMouseUp : 1;
}
@property(readonly, assign) UITextView* textView;
@property(assign, nonatomic) CGPoint contentOffset;
@property(readonly, assign, nonatomic) BOOL contentContainsNonWhitespaceCharacters;
@property(readonly, assign, nonatomic) NSString* summary;
@property(readonly, assign, nonatomic) NSString* title;
@property(assign, nonatomic) BOOL editable;
@property(assign, nonatomic) BOOL containsCJK;
@property(assign, nonatomic) id<NoteContentLayerDelegate> delegate;
-(void).cxx_destruct;
-(void)scrollView:(id)view setContentOffset:(CGPoint)offset;
-(BOOL)textView:(id)view shouldChangeTextInRange:(NSRange)range replacementText:(id)text;
-(void)textViewDidEndEditing:(id)textView;
-(void)textViewDidBeginEditing:(id)textView;
-(void)textViewDidChange:(id)textView;
-(BOOL)textViewShouldBeginEditing:(id)textView;
-(void)scrollToTop;
-(void)dealloc;
-(id)_automationID;
-(BOOL)resignFirstResponder;
-(BOOL)becomeFirstResponder;
-(void)setScrollIndicatorInsets:(UIEdgeInsets)insets;
-(void)flashScrollIndicators;
-(id)contentAsPlainText:(BOOL)text;
-(void)setContent:(id)content isPlainText:(BOOL)text isCJK:(BOOL)cjk;
-(void)forcedSetContainsCJK:(BOOL)cjk;
-(void)layoutSubviews;
-(void)handleKeyboardMove:(id)move;
-(void)handleKeyboardShow:(id)show;
-(void)updateMargins;
-(id)initWithFrame:(CGRect)frame;
-(void)reloadInterface;
-(void)resetTextViewFrame;
-(CGRect)frameForProposedTextViewFrame:(CGRect)proposedTextViewFrame;
-(id)fontForDisplay;
-(CGRect)_contentRectForRect:(CGRect)rect;
@end

