/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileNotes-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UIActionSheetDelegate.h"

@class UIButton, TrashButton;
@protocol NoteNavigationViewDelegate;

__attribute__((visibility("hidden")))
@interface NoteNavigationView : XXUnknownSuperclass <UIActionSheetDelegate> {
	id _delegate;
	UIButton* _leftButton;
	UIButton* _rightButton;
	UIButton* _shareButton;
	TrashButton* _trashButton;
	int _style;
}
@property(assign, nonatomic) id<NoteNavigationViewDelegate> delegate;
+(void)_loadArtwork;
-(void).cxx_destruct;
-(void)rotationEnded;
-(void)prepareForRotation;
-(void)clicked:(id)clicked event:(GSEventRef)event;
-(BOOL)_sendEvent:(GSEventRef)event forPoint:(CGPoint)point inButton:(id)button action:(id)action;
-(id)shareButton;
-(id)trashButton;
-(void)shareButtonClicked:(id)clicked;
-(void)deleteButtonClicked:(id)clicked;
-(void)rightButtonClicked:(id)clicked;
-(void)leftButtonClicked:(id)clicked;
-(void)setShareButtonEnabled:(BOOL)enabled;
-(void)setTrashButtonEnabled:(BOOL)enabled;
-(void)setRightButtonEnabled:(BOOL)enabled;
-(void)setLeftButtonEnabled:(BOOL)enabled;
-(void)_setButton:(id)button enabled:(BOOL)enabled;
-(void)layoutSubviews;
-(void)_layoutButton:(id)button ofType:(int)type forBounds:(CGRect)bounds withLayout:(int)layout landscapeOffset:(int)offset;
-(id)initWithFrame:(CGRect)frame backgroundViewStyle:(int)style;
@end

