/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UINavigationController, UIImageView, NotesSideNavigationController;

__attribute__((visibility("hidden")))
@interface NotesMainViewController : XXUnknownSuperclass {
	NotesSideNavigationController* _leftNavController;
	UINavigationController* _rightNavController;
	UIImageView* _leftImageView;
	UIImageView* _backgroundView;
	UIImageView* _pouchView;
	BOOL _restorePopover;
}
@property(assign) UINavigationController* rightNavController;
@property(retain) NotesSideNavigationController* leftNavController;
-(void).cxx_destruct;
-(void)_setupRoundedCorners;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)resetViewFrame;
-(void)loadView;
-(void)updateViewControllers;
-(void)dealloc;
-(id)init;
@end

