/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileNotes-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface NotesNavigationBar : XXUnknownSuperclass {
}
-(void)drawBackgroundInRect:(CGRect)rect withStyle:(int)style;
-(void)layoutSubviews;
@end

