/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileNotes-Structs.h"
#import "NotesTableView.h"

@class UILabel, UISearchBar, UIImageView;

__attribute__((visibility("hidden")))
@interface NotesListTableView : NotesTableView {
	UIImageView* _selectionView;
	UILabel* _emptyContentLabel;
	UISearchBar* _searchBar;
	BOOL _didSendToBack;
	unsigned _selectionNumber;
}
@property(assign, nonatomic) unsigned selectionNumber;
@property(assign, nonatomic) UISearchBar* searchBar;
-(void).cxx_destruct;
-(void)cancelSelectionAnimation;
-(void)animateSelection;
-(BOOL)updateSelection;
-(void)hideSelection;
-(void)setContentOffset:(CGPoint)offset;
-(void)layoutSubviews;
-(void)insertSubview:(id)subview atIndex:(int)index;
-(void)dealloc;
-(void)setEmptyLabel:(id)label;
-(void)setShowsEmptyLabel:(BOOL)label;
-(id)initWithFrame:(CGRect)frame style:(int)style;
@end

