/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileNotes-Structs.h"
#import "NotesTableView.h"


__attribute__((visibility("hidden")))
@interface NotesAccountsTableView : NotesTableView {
}
-(id)initWithFrame:(CGRect)frame style:(int)style;
@end

