/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface NotesAnimationQueueObject : XXUnknownSuperclass {
	int _direction;
	unsigned _count;
	unsigned _maxCount;
	BOOL _batch;
	double _lastTappedTime;
}
@property(assign, nonatomic) double lastTappedTime;
@property(assign, nonatomic) BOOL batch;
@property(assign, nonatomic) unsigned maxCount;
@property(assign, nonatomic) unsigned count;
@property(assign, nonatomic) int direction;
-(id)initWithDirection:(int)direction;
@end

