/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NotesBackgroundViewDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface ResumableViewController : XXUnknownSuperclass <NotesBackgroundViewDelegate> {
	NSDictionary* _archivedConfiguration;
}
+(void)loadMessageUIIfNecessary;
-(void).cxx_destruct;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(BOOL)controllerIsInLandscapeMode;
-(void)viewDidLoad;
-(BOOL)applyNonUIArchivedConfiguration:(id)configuration;
-(void)applyArchivedConfiguration:(id)configuration;
-(id)init;
-(id)initWithArchivedConfiguration:(id)archivedConfiguration;
-(id)archivedConfiguration;
@end

