/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileNotes-Structs.h"
#import "SuckAnimationDestination.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImageView;

__attribute__((visibility("hidden")))
@interface TrashButton : XXUnknownSuperclass <SuckAnimationDestination> {
	id _delegate;
	UIImageView* _trashLid;
	UIImageView* _trashCan;
}
@property(assign, nonatomic) id delegate;
-(void).cxx_destruct;
-(CGPoint)suckPointInView;
-(void)trashClosed;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
-(void)wiggleTrash;
-(id)_transformForWiggleToDegrees:(float)degrees height:(float)height;
-(void)closeTrash;
-(void)trashOpened;
-(void)openTrashInView:(id)view;
@end

