/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileNotes-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface XXUnknownSuperclass (Summarization)
-(id)firstLine;
-(BOOL)containsNonWhitespaceCharacters;
-(id)summary;
-(BOOL)_appendTextContentsOfNode:(id)node maxLength:(int)length skippingFirstLine:(BOOL*)line toString:(id)string;
@end

@interface XXUnknownSuperclass (Summarization)
-(BOOL)containsNonWhitespaceCharacters;
-(BOOL)isSeparatingTag;
-(BOOL)isBreakingTag;
-(BOOL)isStyleTag;
@end

@interface XXUnknownSuperclass (NotesDateUtilities)
-(id)dateDeltaString;
-(id)userFriendlyString;
-(id)userFriendlyStringWithTime;
-(XXStruct_fhKmAA)day;
@end

